import { NaiveBayes } from "./naive-bayes";

export type ClassifierIntent = "greeting" | "thanks" | "help" | "trending_tokens" | "other";

const TRAINING: Record<ClassifierIntent, string[]> = {
  greeting: [
    "hi",
    "hii",
    "hiii",
    "hello",
    "hello there",
    "hello tokenmind",
    "hey",
    "hey there",
    "hey buddy",
    "hey man",
    "hiya",
    "yo",
    "yoo",
    "yooo",
    "sup",
    "wsup",
    "wassup",
    "what's up",
    "whats up",
    "whats good",
    "what is up",
    "gm",
    "gn",
    "good morning",
    "good afternoon",
    "good evening",
    "morning",
    "evening",
    "howdy",
    "greetings",
    "hey how are you",
    "hi how's it going",
    "how are you",
    "how's it going",
    "how you doing",
    "helo",
    "helllo",
    "hey!",
    "hi?",
    "yo!",
    "hola",
    "salutations",
  ],

  thanks: [
    "thanks",
    "thank you",
    "thank you so much",
    "thanks a lot",
    "thanks a ton",
    "thanks a bunch",
    "many thanks",
    "appreciate it",
    "really appreciate it",
    "much appreciated",
    "cheers",
    "thx",
    "ty",
    "tysm",
    "thank u",
    "thankyou",
    "thnks",
    "thanks!",
    "cool thanks",
    "sweet thanks",
    "perfect thanks",
    "great thanks",
    "awesome thank you",
    "got it thanks",
    "that helps thanks",
    "thanks for that",
    "thanks for the help",
    "thanks for the list",
    "ok thanks",
    "alright thanks",
    "nice thanks",
  ],

  help: [
    "help",
    "help me",
    "help me please",
    "please help",
    "can you help",
    "can you help me",
    "could you help me",
    "i need help",
    "need assistance",
    "assist me",
    "guide me",
    "what can you do",
    "what do you do",
    "what are you able to do",
    "show me your features",
    "list your features",
    "list your commands",
    "how do you work",
    "how does this work",
    "how do i use this",
    "explain what you do",
    "what are your capabilities",
    "what is tokenmind",
    "who are you",
    "what is this app",
    "what is this bot",
    "i'm confused how do i use this",
    "im lost what can you do",
    "how can you help me",
    "what should i ask you",
    "give me an example of what to ask",
    "commands",
    "menu",
  ],

  trending_tokens: [
    "trending",
    "trending tokens",
    "trending coins",
    "show trending tokens",
    "show me trending tokens",
    "show trending",
    "what are the top coins",
    "what are the top tokens",
    "top tokens",
    "top coins",
    "top 10 tokens",
    "top 10 coins",
    "popular solana tokens",
    "popular tokens",
    "popular coins",
    "which tokens are hot",
    "which coins are hot",
    "hot tokens",
    "hot tokens right now",
    "hot coins today",
    "top crypto coins",
    "what's trending in solana",
    "whats trending on solana",
    "what's trending on solana right now",
    "whats trending on solana right now",
    "give me trending coins",
    "give me trending tokens",
    "show me popular tokens",
    "which coins are rising",
    "what's popping right now",
    "any hot tokens today",
    "i want to see the lists of trending tokens",
    "can you show me what's trending on solana right now",
    "i'm curious what tokens are hot at the moment",
    "give me a list of top performing tokens today",
    "what tokens are gaining right now",
    "gainers today",
    "solana gainers",
    "what's pumping on solana",
    "whats pumping right now",
    "memecoins trending",
    "trending memes on solana",
    "hottest solana tokens",
    "show me the hottest tokens",
    "list trending solana coins",
    "what's moving on solana",
    "tokens with volume today",
    "current trending list",
    "trnding tokens",
    "trendng tokens",
    "pls show trending tokens",
    "please show me trending coins",
    "lfg what's trending",
    "hey what's trending on solana",
    "hi show me trending tokens",
    "yo what tokens are hot",
    "gm what's trending",
    "can u show trending tokens",
    "i wanna see what's trending",
    "you know it is kind of crazy but i have to see the lists of trending tokens",
  ],

  other: [
    "what's the anchor framework",
    "how does staking work on solana",
    "how does staking work",
    "explain staking on solana",
    "what is an spl token",
    "what is a solana program",
    "explain proof of history",
    "tell me about metaplex",
    "how do solana transactions work",
    "what is a pda",
    "help me understand staking",
    "can you help me understand rust on solana",
    "help me swap tokens",
    "help me find this token",
    "swap 1 sol to usdc",
    "i want to convert sol to bonk",
    "exchange my tokens",
    "swap sol for usdc",
    "how do i swap",
    "tell me about this token",
    "tell me about this token 61V8vBaqAGMpgDQi4JcAwo1dmBGHsyhzodcPqnEVpump",
    "get info for this contract address",
    "token info for So11111111111111111111111111111111111111112",
    "what's the price of bonk",
    "price of sol",
    "show me chart for this mint",
    "why is bonk trending down today",
    "why is this token trending",
    "why are these tokens trending",
    "what caused the price drop",
    "explain why this token is pumping",
    "explain why solana tokens are hot",
    "reason these coins are trending",
    "what's trending on twitter",
    "whats trending on twitter",
    "what's trending on crypto twitter",
    "crypto twitter trends",
    "trending on x",
    "twitter trending crypto",
    "i lost money on that token",
    "should i buy this coin",
    "is this a rug",
    "what's the weather like",
    "tell me a joke",
    "who is the president",
    "write me a poem",
    "ok",
    "cool",
    "nice",
    "yes",
    "no",
    "maybe later",
    "nevermind",
    "stop",
    "asdfgh",
    "????",
  ],
};

const nb = new NaiveBayes();

for (const [intent, examples] of Object.entries(TRAINING) as [ClassifierIntent, string[]][]) {
  for (const example of examples) {
    nb.learn(example, intent);
  }
}

export { nb };
